### ISSUE TITLE
Weight taxa/autocomplete results by preferred_place_id

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#117] opened 2018-01-09 20:51 UTC
Closely related to #115: if the request has a preferred_place_id, can we weight results by whether or not the matching taxon name is associated with the preferred place? @tiwane, since you requested this (or at least relayed the request), can you provide some concrete examples of search terms and what shows up now vs what people want to show up?

**Comment by tiwane** [comment] 2018-01-13 00:29
This is a possible solution for the debate about using a duplicate common name with a taxon, generally in regards to subspecies.

Currently, our policy doesn’t allow the common name of an infrataxon to be a duplicate of of its parent, eg Junonia hierta ssp. cebrene is the only ssp of J. hierta that occurs in southern Africa, and everyone there calls it the Yellow Pansy, but that happens to be the global common name of J. hierta, so Yellow Pansy can’t be the global subspecies name. So if a layperson in southern Africa types in Yellow Pansy, the subspecies won’t show up and they’ll have to settle for just a species-level ID. Furthermore, typing in Yellow Pansy surfaces this, because right now (I think?) results are ordered by the number of observations each taxon has:

<img width="673" alt="screen shot 2018-01-11 at 11 53 23 am" src="https://user-images.githubusercontent.com/15896181/34845485-d44c1fb6-f6c9-11e7-83a3-d0270b7333b9.png">

If it’s possible to weight searches by one’s preferred_place_id, _and_ allow infraspecies duplicate common names (for a Place), then the hope is that Junonia hierta ssp. cebrene would pop-up at the top, if one happened to be living in southern Africa.

**Comment by loarie** [comment] 2018-01-30 19:34
> If it’s possible to weight searches by one’s preferred_place_id, and allow infraspecies duplicate common names (for a Place), then the hope is that Junonia hierta ssp. cebrene would pop-up at the top, if one happened to be living in southern Africa.

So if there was a common name Yellow Pansy added to Junonia hierta ssp. cebrene (with a place of South Africa) that matched the common name Yellow Pansy added to Junonia hierta.

If I had US associated with my account and typed in Yellow Pansy what would happen?

If I had no Place associated with my account and typed in Yellow Pansy what would happen?

**Comment by tiwane** [comment] 2018-01-31 20:25
Good point. I would imagine the taxon with a global name common name (J. hierta) would be at the top, displayed with the common name. Below would be J. hierta ssp cebrene not displaying a common name. 

Would it matter if you had US or no Place set, as long as there were no place-based common names set globally or for the US?

**Comment by loarie** [comment] 2018-01-31 20:42
I guess where I'm getting confused here is that under the current system we don't really have the concept of a 'global name' being distinct from a local name. All names are 'global' and some are also associated with one or more places.  But there's no way to say this name is associated with this place but shouldn't be used as a global name. Is that going to be a problem?

**Comment by tiwane** [comment] 2018-01-31 20:59
So you're saying that currently, because J. h. cebrene will have Yellow Pansy as its common name, even if only for a certain place, that name will still be found and displayed if I don't have a place setting for my account? 

I can present this to the GG and see if something like that is workable for those who are passionate about it, so we don't use Ken-ichi's time on something that won't satisfy them.

**Comment by tiwane** [comment] 2018-01-31 21:01
Would it be possible to have a Place-based name not be part of the "global name" list?

**Comment by loarie** [comment] 2018-01-31 21:07
>Would it be possible to have a Place-based name not be part of the "global name" list?
Not without allowing duplicates of the same name within a taxon/lexicon 

If I'm reading you right and you're saying the answers to my questions would be:
>If I had US associated with my account and typed in Yellow Pansy what would happen?
I wouldn't see J. hierta ssp cebrene

>If I had no Place associated with my account and typed in Yellow Pansy what would happen?
I would see J. hierta ssp cebrene

I think that sounds reasonable to me because anyone who really didn't want to see the local name for J. hierta ssp cebrene could do so by setting a place on their account. But curious what @kueda thinks

**Comment by pleary** [comment] 2018-01-31 21:12
Personally, I think it'd be weird if we knew taxon was called "Yellow Pansy" in English in somewhere, but if I typed that name in I might not get it in a search results just because I have a different place set. I can see how places would be use to prioritize search results, but shouldn't searches be inclusive? Maybe it could be lower on the list, but to not return it at all seems like it would make search more confusing

**Comment by tiwane** [comment] 2018-01-31 21:26
That's a good point. I _think_ the ability to use duplicate common names for subspecies (which place-based search results ranking would achieve) would likely palliate most people. 

Scott, to respond to your last post, I hadn't imagined that having US be your place setting or having no place setting would have a different effect on the results. I imagined that either way it would show: 1st Yellow Pansy (j. hierta) and then the different subspecies, sans common names, to make them less enticing for a novice.

**Closed** 2018-02-13 00:47 UTC
Labels: improvements
